FROM postgres:16-alpine

# Доп. пакеты при необходимости
# RUN apk add --no-cache postgresql-contrib

# Конфиг и init-скрипты ожидаются томами в compose:
# - ../db/postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf:ro
# - ../db/postgres/initdb:/docker-entrypoint-initdb.d:ro
